### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by bripc** [CodeAllianceOrg/odk2#9]
From the UI layout as it currently stands, I'm having difficulty deciphering how to use the form builder in order to make it accessible to others. In order to make it accessible for everyone I'd like to know what a few things are:
- What are "Groups"? Is it related questions? Is it the entire survey that you then export?
- Is there more than one form in a survey?
- Can you currently make more than just a text question / do you switch Form Elements by clicking on them or another way?
- What are the "Properties"? I see "Base" is kind of a title of a question? What is the "Display" and does it display anywhere yet?
- What do the buttons in the top left do in a group? I see a trash can (delete I can see) and reordering arrows but I can't tell what the checkbox does and why it turns into a list icon?

Current UI Layout:
![screen shot 2017-10-11 at 6 40 11 pm](https://user-images.githubusercontent.com/10554893/31475092-a8a3104e-aeb3-11e7-8bc8-f87367d78077.png)

**Comment by johnhbenetech** [comment]
My take on it:

1. Groups are equivalent to 'Sections' in ODK 2.0 speak. Each group of questions will display on a single page in the mobile app. There can be multiple groups in a survey, and hitting 'next/prev' in the app carries you through the screens.

2. No, One form, One Survey. I think Tristan just added the 'New Form' tab paradigm because it was easy to do. We can remove this for now if we want.

3. It seems only the text question is possible right now. To create a text question you should use the grey 'checkbox' button to select the group into which you want the text question to be added.

4. Properties are we we would capture the ODK 2.0 columns data for each question. So there are a ton of options that could possibly appear here. For now, we have two basic concepts: 1. 'Base' - this is like the machine readable name for the question so like 'UserIncome1', 2. 'Display' - These are the strings that will be rendered to the user when taking the survey in the app. you can supply Display text for any number of languages you wish.

5. Yeah so trash, reorder up, reorder down. The checkbox is a way to select the group into which new questions should be added. So like if I was currently working in group 1, but I wanted to add a text question to group 3, i would first hit the group 3 checkbox and then hit the text button.


Currently the export button isn't hooked up either. Theoretically though the user flow would be:
1. User creates new survey including groups - questions - properties.
2. User hits export to received a xlsx properly formatted to ODK 2.0 standard
3. User can use this file with their ODK 2.0 system to load this form onto their survey
4. If updates need to be made, the user can upload their previous xlsx, which will populate the formbuilder with the existing survey. The form can be updated and re-exported.

**Comment by russon77** [comment]
honestly not sure where the semantics originated, but we should synchronize - let's change `group` to `section` and `form` to `survey`. 

selection is very basic, we're using fontawesome http://fontawesome.io/ and well i just kinda grabbed some icons at a glance haha. i'm up to switch or add another icon library.

**Comment by bripc** [comment]
I spent some time rearranging the current UI, renaming the sections, and adding hidden items for accessibility. Let me know your thoughts on this and then I'll push.

My thoughts are that the different sections on the right don't appear unless they are available as options for editing the survey. Currently the titles and question types are always there but I think they should be hidden by default.

![screen shot 2017-10-17 at 2 04 02 pm](https://user-images.githubusercontent.com/10554893/31689382-1a646162-b344-11e7-913a-36e6b2e2b5ce.png)

**Comment by russon77** [comment]
the idea behind having one panel on each side is to collapse on smaller screen sizes into "drawers" that pop up from either side, like how https://www.jotform.com/build/ handles "add form element" and "element properties".

that said, i'm not sure the best way to approach this for accessibility (and simplicity!). i would guess that collapsible menus *aren't* a great strategy, and the current Prompt Type area takes up a lot of space than it needs to. hmm.

we could create a horizontal list of icons or text like https://build.opendatakit.org/ , kind of like how @johnhbenetech had talked about, placed inside of the individual survey sections.

**Comment by johnhbenetech** [comment]
I like the labels, icons, and help text throughout. +1

I'm not sure about hiding the prompt types by default. I agree they can be moved somewhere else, and that they should have some indication when they are clickable vs when they are not.

My concern is that without those I'm not sure a user would know what their first action should be. 

One idea: maybe a blank form should start with a single empty (undeletable?) section by default. In that way, the user should at all times be able to add questions.

Medium term: I like the horizontal list of buttons
